// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAui10TK4qUXud-sC2m06tF-_yTxIAJ3Vw',
    appId: '1:716899620693:web:3beaa314a5fe115cae41dc',
    messagingSenderId: '716899620693',
    projectId: 'e-comer-bd3fd',
    authDomain: 'e-comer-bd3fd.firebaseapp.com',
    storageBucket: 'e-comer-bd3fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaOZAoWFEBaGO63yVf3usFMWX53BLpCKo',
    appId: '1:716899620693:android:c18775c681f612fdae41dc',
    messagingSenderId: '716899620693',
    projectId: 'e-comer-bd3fd',
    storageBucket: 'e-comer-bd3fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-7m5Vwbm8MBkfLAlFo6t8Dj0zX0YF5M0',
    appId: '1:716899620693:ios:4eb4126c9d2e2d9fae41dc',
    messagingSenderId: '716899620693',
    projectId: 'e-comer-bd3fd',
    storageBucket: 'e-comer-bd3fd.appspot.com',
    iosBundleId: 'com.example.flutterApplicationEComerce2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-7m5Vwbm8MBkfLAlFo6t8Dj0zX0YF5M0',
    appId: '1:716899620693:ios:2bcb36b695b8f226ae41dc',
    messagingSenderId: '716899620693',
    projectId: 'e-comer-bd3fd',
    storageBucket: 'e-comer-bd3fd.appspot.com',
    iosBundleId: 'com.example.flutterApplicationEComerce2.RunnerTests',
  );
}
